const MOCK_ASSETS = [
  {
    id: "1JJzf4oPaNvaFJOFI0PN7C",
    title: "nooma 3Seater ToomModularSofa OatmilkBeige-10",
    url: "/assets/nooma_3Seater_ToomModularSofa_OatmilkBeige-10.jpg",
    thumbnail: "/assets/nooma_3Seater_ToomModularSofa_OatmilkBeige-10.jpg",
    width: 1581,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "798RN6UUuf3q75BarMgtw7",
    title: "nooma 3Seater ToomModularSofa OatmilkBeige-7",
    url: "/assets/nooma_3Seater_ToomModularSofa_OatmilkBeige-7.jpg",
    thumbnail: "/assets/nooma_3Seater_ToomModularSofa_OatmilkBeige-7.jpg",
    width: 1580,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "5EILfWfK4V94akJMnXM8WL",
    title: "nooma 6Seater ToomModularSofa PaleGrey-4",
    url: "/assets/nooma_6Seater_ToomModularSofa_PaleGrey-4.jpg",
    thumbnail: "/assets/nooma_6Seater_ToomModularSofa_PaleGrey-4.jpg",
    width: 1581,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "URTA2QAgHTKtPfNh4j2dJ",
    title: "nooma 3Seater ToomModularSofa OatmilkBeige-4",
    url: "/assets/nooma_3Seater_ToomModularSofa_OatmilkBeige-4.jpg",
    thumbnail: "/assets/nooma_3Seater_ToomModularSofa_OatmilkBeige-4.jpg",
    width: 2370,
    height: 1580,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "2CpiV2m8QjPxuMNrODmevs",
    title: "nooma 6Seater ToomModularSofa PaleGrey-2",
    url: "/assets/nooma_6Seater_ToomModularSofa_PaleGrey-2.jpg",
    thumbnail: "/assets/nooma_6Seater_ToomModularSofa_PaleGrey-2.jpg",
    width: 1777,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "11LxSNilpYQ2naemuA0iEb",
    title: "nooma 6Seater ToomModularSofa PaleGrey-1-1",
    url: "/assets/nooma_6Seater_ToomModularSofa_PaleGrey-1-1.jpg",
    thumbnail: "/assets/nooma_6Seater_ToomModularSofa_PaleGrey-1-1.jpg",
    width: 2370,
    height: 1581,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "vwbyVBPYqlNLBlJarGZgr",
    title: "nooma 3Seater ToomModularSofa OatmilkBeige-1",
    url: "/assets/nooma_3Seater_ToomModularSofa_OatmilkBeige-1.jpg",
    thumbnail: "/assets/nooma_3Seater_ToomModularSofa_OatmilkBeige-1.jpg",
    width: 1580,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "6IHFPBtB28lQkHJtftaMAM",
    title: "nooma 3Seater ToomModularSofa OatmilkBeige-8",
    url: "/assets/nooma_3Seater_ToomModularSofa_OatmilkBeige-8.jpg",
    thumbnail: "/assets/nooma_3Seater_ToomModularSofa_OatmilkBeige-8.jpg",
    width: 1580,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "7kexIQZtpH11TBsk1mQEY7",
    title: "nooma 3Seater ToomModularSofa OatmilkBeige-6",
    url: "/assets/nooma_3Seater_ToomModularSofa_OatmilkBeige-6.jpg",
    thumbnail: "/assets/nooma_3Seater_ToomModularSofa_OatmilkBeige-6.jpg",
    width: 1580,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "5k8eIgLTcHkwc4JWnMqnOT",
    title: "nooma 3Seater ToomModularSofa OatmilkBeige-5",
    url: "/assets/nooma_3Seater_ToomModularSofa_OatmilkBeige-5.jpg",
    thumbnail: "/assets/nooma_3Seater_ToomModularSofa_OatmilkBeige-5.jpg",
    width: 1580,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "7bcuTOTza2VVj43fqVCeOI",
    title: "nooma 3Seater ToomModularSofa OatmilkBeige-3",
    url: "/assets/nooma_3Seater_ToomModularSofa_OatmilkBeige-3.jpg",
    thumbnail: "/assets/nooma_3Seater_ToomModularSofa_OatmilkBeige-3.jpg",
    width: 2370,
    height: 1580,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "4iLYBNvflCX3b0Rp0XF5nY",
    title: "nooma 2Seater ToomModularSofa PaleGrey-1-1",
    url: "/assets/nooma_2Seater_ToomModularSofa_PaleGrey-1-1.jpg",
    thumbnail: "/assets/nooma_2Seater_ToomModularSofa_PaleGrey-1-1.jpg",
    width: 2370,
    height: 1581,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "1bY2YNFVREIl6ddHb8nSyF",
    title: "nooma 2Seater ToomModularSofa PaleGrey-3",
    url: "/assets/nooma_2Seater_ToomModularSofa_PaleGrey-3.jpg",
    thumbnail: "/assets/nooma_2Seater_ToomModularSofa_PaleGrey-3.jpg",
    width: 1581,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "6oxZ7L87BLWEcSFdodEAe1",
    title: "nooma 2Seater ToomModularSofa PaleGrey-2",
    url: "/assets/nooma_2Seater_ToomModularSofa_PaleGrey-2.jpg",
    thumbnail: "/assets/nooma_2Seater_ToomModularSofa_PaleGrey-2.jpg",
    width: 1581,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "1EfvgzIvaX4hK5viWhGBcE",
    title: "nooma 2Seater ToomModularSofa PaleGrey-4",
    url: "/assets/nooma_2Seater_ToomModularSofa_PaleGrey-4.jpg",
    thumbnail: "/assets/nooma_2Seater_ToomModularSofa_PaleGrey-4.jpg",
    width: 1581,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "2XhEtWaMqKhmFFISA20NRW",
    title: "nooma FUR1432 TeidiShelving Oak-1",
    url: "/assets/nooma_FUR1432_TeidiShelving_Oak-1.jpg",
    thumbnail: "/assets/nooma_FUR1432_TeidiShelving_Oak-1.jpg",
    width: 2370,
    height: 1581,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "7tgq3DeCl05j0PAI4KAZFZ",
    title: "nooma FUR1432 TeidiShelving Oak-5",
    url: "/assets/nooma_FUR1432_TeidiShelving_Oak-5.jpg",
    thumbnail: "/assets/nooma_FUR1432_TeidiShelving_Oak-5.jpg",
    width: 1581,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "Jf9cQClfimL0I5jKanntb",
    title: "avatar-1",
    url: "/assets/avatar-1.jpg",
    thumbnail: "/assets/avatar-1.jpg",
    width: 200,
    height: 250,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "PQN4THtuBfcS1F0PsLicH",
    title: "nooma FUR1732 AtikBedsideTable Oak-5 2-inverted",
    url: "/assets/nooma_FUR1732_AtikBedsideTable_Oak-5_2-inverted.png",
    thumbnail: "/assets/nooma_FUR1732_AtikBedsideTable_Oak-5_2-inverted.png",
    width: 1440,
    height: 745,
    mimeType: "image/png",
    isVideo: false,
  },
  {
    id: "3mfsxEihl1DCQbIfb0Heh2",
    title: "nooma ACC1092 OulServingPlatterBowls-4",
    url: "/assets/nooma_ACC1092_OulServingPlatterBowls-4.jpg",
    thumbnail: "/assets/nooma_ACC1092_OulServingPlatterBowls-4.jpg",
    width: 2370,
    height: 1581,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "nPeArtLJhInZw8CYb4sjl",
    title: "nooma ACC1071 IksTrivet Oak-6",
    url: "/assets/nooma_ACC1071_IksTrivet_Oak-6.jpg",
    thumbnail: "/assets/nooma_ACC1071_IksTrivet_Oak-6.jpg",
    width: 2370,
    height: 1581,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "b3h4SyrjadkmOzn1chdMo",
    title: "nooma ACC1092 OulServingPlatterBowls-5-1",
    url: "/assets/nooma_ACC1092_OulServingPlatterBowls-5-1.jpg",
    thumbnail: "/assets/nooma_ACC1092_OulServingPlatterBowls-5-1.jpg",
    width: 1581,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "3VbjFZXsf44VTXLbSquoMI",
    title: "nooma ACC1092 OulServingPlatterBowls-3",
    url: "/assets/nooma_ACC1092_OulServingPlatterBowls-3.jpg",
    thumbnail: "/assets/nooma_ACC1092_OulServingPlatterBowls-3.jpg",
    width: 1581,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "1nKoU715wNx8NebquprUZh",
    title: "nooma ACC1071 IksTrivet Oak-1",
    url: "/assets/nooma_ACC1071_IksTrivet_Oak-1.jpg",
    thumbnail: "/assets/nooma_ACC1071_IksTrivet_Oak-1.jpg",
    width: 1581,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "3AIUapYWAq9kKZarDl2GW",
    title: "nooma ACC1071 IksTrivet Oak-3",
    url: "/assets/nooma_ACC1071_IksTrivet_Oak-3.jpg",
    thumbnail: "/assets/nooma_ACC1071_IksTrivet_Oak-3.jpg",
    width: 1581,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "3Ty4OSVqTq7si3i27fovrc",
    title: "nooma ACC1062 FalaBookend MellowYellow-1",
    url: "/assets/nooma_ACC1062_FalaBookend_MellowYellow-1.jpg",
    thumbnail: "/assets/nooma_ACC1062_FalaBookend_MellowYellow-1.jpg",
    width: 1334,
    height: 2000,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "2S7lwAKRDhY0dPN3PUNqev",
    title: "nooma ACC1071 IksTrivet Oak-4",
    url: "/assets/nooma_ACC1071_IksTrivet_Oak-4.jpg",
    thumbnail: "/assets/nooma_ACC1071_IksTrivet_Oak-4.jpg",
    width: 1581,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "D187tdccMo9xQ3JYNcIDW",
    title: "nooma ACC1062 FalaBookend MellowYellow-2",
    url: "/assets/nooma_ACC1062_FalaBookend_MellowYellow-2.jpg",
    thumbnail: "/assets/nooma_ACC1062_FalaBookend_MellowYellow-2.jpg",
    width: 1334,
    height: 2000,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "6s8ClABm9tBu6gOTomkgGi",
    title: "nooma ACC1071 IksTrivet Oak-5",
    url: "/assets/nooma_ACC1071_IksTrivet_Oak-5.jpg",
    thumbnail: "/assets/nooma_ACC1071_IksTrivet_Oak-5.jpg",
    width: 1581,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "5MPqA8chK9SdwEiiYoGtvr",
    title: "nooma ACC1071 IksTrivet Oak-2-1",
    url: "/assets/nooma_ACC1071_IksTrivet_Oak-2-1.jpg",
    thumbnail: "/assets/nooma_ACC1071_IksTrivet_Oak-2-1.jpg",
    width: 2370,
    height: 1581,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "6pQ5dJeucfcnmBtZfDV9MI",
    title: "nooma FlecCandleHolder-Set-4-1",
    url: "/assets/nooma_FlecCandleHolder-Set-4-1.jpg",
    thumbnail: "/assets/nooma_FlecCandleHolder-Set-4-1.jpg",
    width: 2370,
    height: 1581,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "6ULhRvjt92DY1mw3i0m27L",
    title: "nooma FlecCandleHolder-Low-PiazzaBeige-2",
    url: "/assets/nooma_FlecCandleHolder-Low-PiazzaBeige-2.jpg",
    thumbnail: "/assets/nooma_FlecCandleHolder-Low-PiazzaBeige-2.jpg",
    width: 1581,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "7fNcnljPkE85AYOqZDGtHf",
    title: "nooma 6Seater ToomModularSofa PaleGrey-5",
    url: "/assets/nooma_6Seater_ToomModularSofa_PaleGrey-5.jpg",
    thumbnail: "/assets/nooma_6Seater_ToomModularSofa_PaleGrey-5.jpg",
    width: 1581,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "35Vsxmpc81XmOhkLrBHDRJ",
    title: "nooma FlecCandleHolder-Set-3",
    url: "/assets/nooma_FlecCandleHolder-Set-3.jpg",
    thumbnail: "/assets/nooma_FlecCandleHolder-Set-3.jpg",
    width: 1581,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "4nzjxp5qpIzpTG5wn79iPu",
    title: "nooma 6Seater ToomModularSofa PaleGrey-2",
    url: "/assets/nooma_6Seater_ToomModularSofa_PaleGrey-2.png",
    thumbnail: "/assets/nooma_6Seater_ToomModularSofa_PaleGrey-2.png",
    width: 1581,
    height: 2370,
    mimeType: "image/png",
    isVideo: false,
  },
  {
    id: "4v6uAaZYCH7GEo0JPxf7M9",
    title: "nooma 6Seater ToomModularSofa PaleGrey-3",
    url: "/assets/nooma_6Seater_ToomModularSofa_PaleGrey-3.jpg",
    thumbnail: "/assets/nooma_6Seater_ToomModularSofa_PaleGrey-3.jpg",
    width: 2370,
    height: 1581,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "65uE0RAPnSy4zqJYQYXnWg",
    title: "nooma 3Seater ToomModularSofa OatmilkBeige-9",
    url: "/assets/nooma_3Seater_ToomModularSofa_OatmilkBeige-9.jpg",
    thumbnail: "/assets/nooma_3Seater_ToomModularSofa_OatmilkBeige-9.jpg",
    width: 1580,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "6bkaao6oq2mG0cCdKNoxRs",
    title: "nooma FUR1732 AtikBedsideTable Oak-4-1",
    url: "/assets/nooma_FUR1732_AtikBedsideTable_Oak-4-1.png",
    thumbnail: "/assets/nooma_FUR1732_AtikBedsideTable_Oak-4-1.png",
    width: 2370,
    height: 1580,
    mimeType: "image/png",
    isVideo: false,
  },
  {
    id: "5qxmxvIN0HKnVxdufoK4C2",
    title: "nooma FUR1143 FolkPoufTall EveningBlue-1-1",
    url: "/assets/nooma_FUR1143_FolkPoufTall_EveningBlue-1-1.png",
    thumbnail: "/assets/nooma_FUR1143_FolkPoufTall_EveningBlue-1-1.png",
    width: 2370,
    height: 1566,
    mimeType: "image/png",
    isVideo: false,
  },
  {
    id: "1OKw4tQ7bmoytLExgwe2D0",
    title: "nooma FUR1422 TeidiShelving Oak-2-1",
    url: "/assets/nooma_FUR1422_TeidiShelving_Oak-2-1.jpg",
    thumbnail: "/assets/nooma_FUR1422_TeidiShelving_Oak-2-1.jpg",
    width: 1581,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "gK51yzEca76X5SVdHzbnJ",
    title: "nooma FUR1422 TeidiShelving Oak-1-1",
    url: "/assets/nooma_FUR1422_TeidiShelving_Oak-1-1.png",
    thumbnail: "/assets/nooma_FUR1422_TeidiShelving_Oak-1-1.png",
    width: 3000,
    height: 2000,
    mimeType: "image/png",
    isVideo: false,
  },
  {
    id: "6VpdFdYvjBx42jRkzlzf8P",
    title: "nooma FUR16032 YamiTableLong Oak-1-1",
    url: "/assets/nooma_FUR16032_YamiTableLong_Oak-1-1.png",
    thumbnail: "/assets/nooma_FUR16032_YamiTableLong_Oak-1-1.png",
    width: 2370,
    height: 1580,
    mimeType: "image/png",
    isVideo: false,
  },
  {
    id: "6aiqE0IqeWfpFSN0iE4tPI",
    title: "nooma 5Seater ToomModularSofa GraphiteBlack-5-1",
    url: "/assets/nooma_5Seater_ToomModularSofa_GraphiteBlack-5-1.png",
    thumbnail: "/assets/nooma_5Seater_ToomModularSofa_GraphiteBlack-5-1.png",
    width: 2000,
    height: 1333,
    mimeType: "image/png",
    isVideo: false,
  },
  {
    id: "2FiKC2sagL7QOBstDWpfEj",
    title: "nooma FUR1732 AtikBedsideTable Oak-2",
    url: "/assets/nooma_FUR1732_AtikBedsideTable_Oak-2.jpg",
    thumbnail: "/assets/nooma_FUR1732_AtikBedsideTable_Oak-2.jpg",
    width: 2370,
    height: 1581,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "ooHwxsscetlBKWUHvDrYv",
    title: "nooma FUR1732 AtikBedsideTable Oak-3",
    url: "/assets/nooma_FUR1732_AtikBedsideTable_Oak-3.jpg",
    thumbnail: "/assets/nooma_FUR1732_AtikBedsideTable_Oak-3.jpg",
    width: 1581,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "3RBlJ4dwQtIajhMM3qeD7B",
    title: "nooma FUR1731 AtikBedsideTable VulcanoBlack-2",
    url: "/assets/nooma_FUR1731_AtikBedsideTable_VulcanoBlack-2.jpg",
    thumbnail: "/assets/nooma_FUR1731_AtikBedsideTable_VulcanoBlack-2.jpg",
    width: 1581,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "1FsVeMZsCJNsy3JLiy8GGo",
    title: "nooma FUR1732 AtikBedsideTable Oak-1-1",
    url: "/assets/nooma_FUR1732_AtikBedsideTable_Oak-1-1.jpg",
    thumbnail: "/assets/nooma_FUR1732_AtikBedsideTable_Oak-1-1.jpg",
    width: 1581,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "SHWatDsF6uCduYvnbzAho",
    title: "nooma FUR1732 AtikBedsideTable Oak-4",
    url: "/assets/nooma_FUR1732_AtikBedsideTable_Oak-4.jpg",
    thumbnail: "/assets/nooma_FUR1732_AtikBedsideTable_Oak-4.jpg",
    width: 1581,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "6ZYzBuqdv0g1FriQGw8vE0",
    title: "nooma FUR1432 TeidiShelving Oak-3",
    url: "/assets/nooma_FUR1432_TeidiShelving_Oak-3.jpg",
    thumbnail: "/assets/nooma_FUR1432_TeidiShelving_Oak-3.jpg",
    width: 1581,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "2iJaD2D0lmX8QF867omHCO",
    title: "nooma FUR1432 TeidiShelving Oak-4",
    url: "/assets/nooma_FUR1432_TeidiShelving_Oak-4.jpg",
    thumbnail: "/assets/nooma_FUR1432_TeidiShelving_Oak-4.jpg",
    width: 1581,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "3WNzDcZ1CrrbRSJeY5xD1k",
    title: "nooma FUR1422 TeidiShelving Oak-1",
    url: "/assets/nooma_FUR1422_TeidiShelving_Oak-1.jpg",
    thumbnail: "/assets/nooma_FUR1422_TeidiShelving_Oak-1.jpg",
    width: 2370,
    height: 1581,
    mimeType: "image/jpeg",
    isVideo: false,
  },
  {
    id: "6oLimElQUkKoUQ0XdtKxPj",
    title: "nooma FUR1432 TeidiShelving Oak-2",
    url: "/assets/nooma_FUR1432_TeidiShelving_Oak-2.jpg",
    thumbnail: "/assets/nooma_FUR1432_TeidiShelving_Oak-2.jpg",
    width: 1581,
    height: 2370,
    mimeType: "image/jpeg",
    isVideo: false,
  },

  {
    id: "2NyETrP9X723XKHdpEzUsD",
    title: "Oly",
    url: "/assets/OLY.mp4",
    thumbnail: "/assets/Screenshot_2022-12-20_at_15.49.59.png",
    width: 2160,
    height: 4096,
    mimeType: "video/mp4",
    isVideo: true,
  },
  {
    id: "6lY5WOjOnvAHuFXXOB6atD",
    title: "Mod Media Furniture",
    url: "/assets/Mod_Media_Furniture.mp4",
    thumbnail: "/assets/Screenshot_2022-12-20_at_15.49.12.png",
    width: 5120,
    height: 2700,
    mimeType: "video/mp4",
    isVideo: true,
  },
  {
    id: "4Cg4pWpGOmgmHP2PPtiONF",
    title: "Met",
    url: "/assets/MET.mp4",
    thumbnail: "/assets/Screenshot_2022-12-20_at_15.48.04.png",
    width: 2160,
    height: 3840,
    mimeType: "video/mp4",
    isVideo: true,
  },
  {
    id: "NLwnsZTiR2B8dSYEaPkT5",
    title: "Ande",
    url: "/assets/ANDE.mp4",
    thumbnail: "/assets/Screenshot_2022-12-20_at_15.46.30.png",
    width: 2160,
    height: 4096,
    mimeType: "video/mp4",
    isVideo: true,
  },
];

export { MOCK_ASSETS };
